name: CI

on:
  - push
  - pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v3
      - name: Check formatting
        run: terraform fmt -check
      - name: Init
        run: terraform init -backend=false
      - name: Validate
        run: terraform validate
